# Generated by Django 5.0.6 on 2024-08-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='user',
        ),
    ]
