# Generated by Django 5.0.6 on 2024-08-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_user_id_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='username',
        ),
    ]
